"""Add security columns for Phase 2

Revision ID: 5d6f333629c8
Revises: f9d0e1f2a3b4
Create Date: 2026-06-28 18:29:20.676180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6f333629c8'
down_revision = 'f9d0e1f2a3b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ai_requests_user'), table_name='ai_requests')
    op.create_index(op.f('ix_ai_requests_user_id'), 'ai_requests', ['user_id'], unique=False)
    op.drop_index(op.f('idx_latency_metrics_created_at'), table_name='latency_metrics')
    op.drop_index(op.f('idx_latency_metrics_user'), table_name='latency_metrics')
    op.drop_index(op.f('idx_latency_metrics_workspace'), table_name='latency_metrics')
    op.create_index(op.f('ix_latency_metrics_created_at'), 'latency_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_latency_metrics_user_id'), 'latency_metrics', ['user_id'], unique=False)
    op.create_index(op.f('ix_latency_metrics_workspace_id'), 'latency_metrics', ['workspace_id'], unique=False)
    op.drop_index(op.f('idx_token_usage_user'), table_name='token_usage')
    op.create_index(op.f('ix_token_usage_user_id'), 'token_usage', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_token_usage_user_id'), table_name='token_usage')
    op.create_index(op.f('idx_token_usage_user'), 'token_usage', ['user_id'], unique=False)
    op.drop_index(op.f('ix_latency_metrics_workspace_id'), table_name='latency_metrics')
    op.drop_index(op.f('ix_latency_metrics_user_id'), table_name='latency_metrics')
    op.drop_index(op.f('ix_latency_metrics_created_at'), table_name='latency_metrics')
    op.create_index(op.f('idx_latency_metrics_workspace'), 'latency_metrics', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_latency_metrics_user'), 'latency_metrics', ['user_id'], unique=False)
    op.create_index(op.f('idx_latency_metrics_created_at'), 'latency_metrics', ['created_at'], unique=False)
    op.drop_index(op.f('ix_ai_requests_user_id'), table_name='ai_requests')
    op.create_index(op.f('idx_ai_requests_user'), 'ai_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###
