"""add_message_rag_metadata

Revision ID: bc1107f3293e
Revises: dec90eb948ca
Create Date: 2026-06-22 17:32:11.522200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc1107f3293e'
down_revision = 'dec90eb948ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ai_requests_workspace'), table_name='ai_requests')
    op.create_index(op.f('ix_ai_requests_workspace_id'), 'ai_requests', ['workspace_id'], unique=False)
    op.drop_index(op.f('idx_conversations_workspace'), table_name='conversations')
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.drop_index(op.f('idx_document_chunks_document'), table_name='document_chunks')
    op.drop_index(op.f('idx_document_chunks_uuid'), table_name='document_chunks')
    op.drop_constraint(op.f('uq_document_chunks_uuid'), 'document_chunks', type_='unique')
    op.create_index(op.f('ix_document_chunks_chunk_uuid'), 'document_chunks', ['chunk_uuid'], unique=True)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.drop_index(op.f('idx_documents_workspace'), table_name='documents')
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.drop_index(op.f('idx_embeddings_chunk'), table_name='embeddings')
    op.drop_index(op.f('idx_embeddings_embedding_hnsw'), table_name='embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_embeddings_chunk_id'), 'embeddings', ['chunk_id'], unique=False)
    op.drop_index(op.f('idx_flashcards_next_review'), table_name='flashcards')
    op.drop_index(op.f('idx_flashcards_note'), table_name='flashcards')
    op.drop_index(op.f('idx_folders_workspace'), table_name='folders')
    op.add_column('messages', sa.Column('model_used', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('retrieved_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('messages', sa.Column('citation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('idx_messages_conversation'), table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_index(op.f('idx_doc_chunks_embedding_hnsw'), table_name='note_document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_document_chunks_note'), table_name='note_document_chunks')
    op.drop_index(op.f('idx_note_versions_note'), table_name='note_versions')
    op.drop_index(op.f('idx_notes_content_trgm'), table_name='notes', postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_notes_creator'), table_name='notes')
    op.drop_index(op.f('idx_notes_folder'), table_name='notes')
    op.drop_index(op.f('idx_notes_title_trgm'), table_name='notes', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_notes_workspace'), table_name='notes')
    op.drop_index(op.f('idx_processing_jobs_document'), table_name='processing_jobs')
    op.create_index(op.f('ix_processing_jobs_document_id'), 'processing_jobs', ['document_id'], unique=False)
    op.drop_index(op.f('idx_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_constraint(op.f('refresh_tokens_token_key'), 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.drop_index(op.f('idx_tags_workspace'), table_name='tags')
    op.drop_index(op.f('idx_token_usage_workspace'), table_name='token_usage')
    op.create_index(op.f('ix_token_usage_workspace_id'), 'token_usage', ['workspace_id'], unique=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('idx_workspace_members_user'), table_name='workspace_members')
    op.drop_index(op.f('idx_workspace_members_workspace'), table_name='workspace_members')
    op.drop_index(op.f('idx_workspaces_slug'), table_name='workspaces')
    op.drop_constraint(op.f('workspaces_slug_key'), 'workspaces', type_='unique')
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.create_unique_constraint(op.f('workspaces_slug_key'), 'workspaces', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_workspaces_slug'), 'workspaces', ['slug'], unique=False)
    op.create_index(op.f('idx_workspace_members_workspace'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_workspace_members_user'), 'workspace_members', ['user_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_token_usage_workspace_id'), table_name='token_usage')
    op.create_index(op.f('idx_token_usage_workspace'), 'token_usage', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_tags_workspace'), 'tags', ['workspace_id'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_unique_constraint(op.f('refresh_tokens_token_key'), 'refresh_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=False)
    op.drop_index(op.f('ix_processing_jobs_document_id'), table_name='processing_jobs')
    op.create_index(op.f('idx_processing_jobs_document'), 'processing_jobs', ['document_id'], unique=False)
    op.create_index(op.f('idx_notes_workspace'), 'notes', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_notes_title_trgm'), 'notes', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_notes_folder'), 'notes', ['folder_id'], unique=False)
    op.create_index(op.f('idx_notes_creator'), 'notes', ['created_by'], unique=False)
    op.create_index(op.f('idx_notes_content_trgm'), 'notes', ['content'], unique=False, postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_note_versions_note'), 'note_versions', ['note_id'], unique=False)
    op.create_index(op.f('idx_document_chunks_note'), 'note_document_chunks', ['note_id'], unique=False)
    op.create_index(op.f('idx_doc_chunks_embedding_hnsw'), 'note_document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index(op.f('idx_messages_conversation'), 'messages', ['conversation_id'], unique=False)
    op.drop_column('messages', 'citation_metadata')
    op.drop_column('messages', 'retrieved_chunks')
    op.drop_column('messages', 'model_used')
    op.create_index(op.f('idx_folders_workspace'), 'folders', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_flashcards_note'), 'flashcards', ['note_id'], unique=False)
    op.create_index(op.f('idx_flashcards_next_review'), 'flashcards', ['next_review'], unique=False)
    op.drop_index(op.f('ix_embeddings_chunk_id'), table_name='embeddings')
    op.create_index(op.f('idx_embeddings_embedding_hnsw'), 'embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_embeddings_chunk'), 'embeddings', ['chunk_id'], unique=False)
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.create_index(op.f('idx_documents_workspace'), 'documents', ['workspace_id'], unique=False)
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_uuid'), table_name='document_chunks')
    op.create_unique_constraint(op.f('uq_document_chunks_uuid'), 'document_chunks', ['chunk_uuid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_document_chunks_uuid'), 'document_chunks', ['chunk_uuid'], unique=False)
    op.create_index(op.f('idx_document_chunks_document'), 'document_chunks', ['document_id'], unique=False)
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.create_index(op.f('idx_conversations_workspace'), 'conversations', ['workspace_id'], unique=False)
    op.drop_index(op.f('ix_ai_requests_workspace_id'), table_name='ai_requests')
    op.create_index(op.f('idx_ai_requests_workspace'), 'ai_requests', ['workspace_id'], unique=False)
    # ### end Alembic commands ###
